name: Interpark Automation

on:
  schedule:
    - cron: '58 1-9 * * *'  # KST 10:58~18:58 (매시 58분)
    - cron: '28 10 * * *'   # KST 19:28
  workflow_dispatch:

jobs:
  run-selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb
          # 크롬, 크롬드라이버 등
          ...

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          INTERPARK_ID: ${{ secrets.INTERPARK_ID }}
          INTERPARK_PW: ${{ secrets.INTERPARK_PW }}
        run: |
          python main.py
